language: generic
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - gcc-multilib
      - linux-libc-dev
      - zlib-dev
cache:
  apt: true
install:
  - pushd $HOME
  - travis_retry git clone https://github.com/luckytyphlosion/agbcc.git -b new_layout_with_libs
  - cd agbcc && make && make install prefix=$TRAVIS_BUILD_DIR
  - popd
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
              - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: _="Build"
      script:
        - make tools CXX=g++-7
        - make -j2 compare
        - make -j2 compare_leafgreen
        - make -j2 compare_firered_rev1
        - make -j2 compare_leafgreen_rev1
after_success:
  - .travis/calcrom/webhook.sh pokefirered
