
#ifndef GUARD_AUTOGENERATED_POKEMON_GROUPS_H
#define GUARD_AUTOGENERATED_POKEMON_GROUPS_H

// +------------------------------------------------------+
// | !!! AUTOGENERATED BY generate_docs_and_groups.py !!! |
// +------------------------------------------------------+

#include "data.h"
#include "global.h"

extern const u16 gGroup_EarlyBoost[19];
extern const u16 gGroup_NormalFlying1[18];
extern const u16 gGroup_NormalFlying2[16];
extern const u16 gGroup_Cave1[22];
extern const u16 gGroup_Cave2[16];
extern const u16 gGroup_GrassBug1[15];
extern const u16 gGroup_GrassBug2[23];
extern const u16 gGroup_GrassBug3[17];
extern const u16 gGroup_Spooky1[20];
extern const u16 gGroup_Spooky2[14];
extern const u16 gGroup_Urban1[17];
extern const u16 gGroup_Urban2[12];
extern const u16 gGroup_WaterIce1[34];
extern const u16 gGroup_WaterIce2[27];
extern const u16 gGroup_Overworld1[37];
extern const u16 gGroup_Overworld2[49];
extern const u16 gGroup_CeruleanCave[6];
extern const u16 gGroup_NotCatchable[30];
extern const u16 gGroup_GrassStarter3[4];
extern const u16 gGroup_FireStarter3[4];
extern const u16 gGroup_WaterStarter3[4];
extern const u16 gGroup_GrassStarter1[4];
extern const u16 gGroup_FireStarter1[4];
extern const u16 gGroup_WaterStarter1[4];
extern const u16* const gMonGroups[651];

#endif
